### ISSUE TITLE
External library for console argument/flag parsing

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2BitmapConverter#5]
I was looking at the gflags library (https://github.com/gflags/gflags).

It is available via vcpkg for Visual Studio builds. I'd be curious if it has a simple packaging tool for Linux builds.

It is also a github project so could be 

Discussion in separate correspondence about keeping the project simple to prevent needing a third party library for flag parsing. This is of course counter to that thought but I am interested in trying one out.

**Comment by DanRStevens** [comment]
Looks like there is an apt package for it, and it's the latest version (2.2.2). Should be easy to support as a dependency.
```
apt install libgflags-dev
```

I looked briefly at the [gflags documentation](https://gflags.github.io/gflags/). Seems like it's macro based. Not sure if I'm a fan of the syntax, though there is probably something to learn from the library. You're welcome to experiment with it.

**Comment by Brett208** [comment]
I was reading a bit more about gflags. Notes are below.

* You can programmatically change flags and then revert those changes. This could be helpful for unit testing maybe?
* Shorthand flags appear to be intentionally not supported. So you have to use the --FullFlagName syntax instead of -f.
* It also intentionally does not allow combining shorthand flags (ie -fq).
* Help messages are autogenerated. You can set usage statement and version number and it will autopopulate flag definitions. It supports a shorthand and longhand help message. Would have to play with it some to see if the format looks acceptable. The auto help message can be disabled. It wasn't clear if you could home roll your own if disabling the auto message.
* If you access a flag in multiple source code files, gflags recommends that you define the flag in a .cpp file and declare it in a .h file similar to a class in cpp 
* Gflags strips the flags and their arguments and then leaves the parent level arguments in main's argv input. It wasn't clear if these could be set programmatically or not. Might be a detriment to the unit testing plus mentioned above depending on how it all shakes out.

I may spend some time reviewing the gflags header. Otherwise probably need to actually play with the library to learn too much more. Likely won't do that until next week though.

**Comment by Brett208** [comment]
Comments below on gflags:

* The syntax for specifying a flag is clean (although not a fan of macros in general)
* The auto-generated help file is a mess

gflags lists the full full location of the source code file (see below) which is a bit mess. It is also specifying which source code file the flag is coming from. Maybe useful for a developer, not not good for end user. Since it recursively searches files, it is listing all flags internal to gflags as well...

I tried using the gflags declaration STRIP_FLAG_HELP to strip the help out. We could just home roll the help file an use gflags to handle the command line parsing. However, this declaration appears to only remove some information from the binary and not actually prevent glflags from handling the help file internally.

There is an open PR to allow removing help information (https://github.com/gflags/gflags/pull/206). It has about 12 'thumbs up' and has been around for about 3 years, but it appears the author has not merged yet.

```
  Flags from C:\Users\Brett\Documents\OutpostUniverseGitHub\OP2BitmapConverter\src\Main.cpp:
    -AccessArchives (Access Outpost 2 volume (.vol) files within the directory
      when searching for bitmaps) type: bool default: true

  Flags from C:\Users\Brett\source\vcpkg\buildtrees\gflags\src\v2.2.2-d9283b9285.clean\src\gflags.cc:
    -flagfile (load flags from file) type: string default: ""
    -fromenv (set flags from the environment [use 'export FLAGS_flag1=value'])
      type: string default: ""
    -tryfromenv (set flags from the environment if present) type: string
      default: ""
    -undefok (comma-separated list of flag names that it is okay to specify on
      the command line even if the program does not define a flag with that
      name.  IMPORTANT: flags in this list that have arguments MUST use the
      flag=value format) type: string default: ""

  Flags from C:\Users\Brett\source\vcpkg\buildtrees\gflags\src\v2.2.2-d9283b9285.clean\src\gflags_completions.cc:
    -tab_completion_columns (Number of columns to use in output for tab
      completion) type: int32 default: 80
    -tab_completion_word (If non-empty, HandleCommandLineCompletions() will
      hijack the process and attempt to do bash-style command line flag
      completion on this value.) type: string default: ""

  Flags from C:\Users\Brett\source\vcpkg\buildtrees\gflags\src\v2.2.2-d9283b9285.clean\src\gflags_reporting.cc:
    -help (show help on all flags [tip: all flags can have two dashes])
      type: bool default: false currently: true
    -helpfull (show help on all flags -- same as -help) type: bool
      default: false
    -helpmatch (show help on modules whose name contains the specified substr)
      type: string default: ""
    -helpon (show help on the modules named by this flag value) type: string
      default: ""
    -helppackage (show help on all modules in the main package) type: bool
      default: false
    -helpshort (show help on only the main module for this program) type: bool
      default: false
    -helpxml (produce an xml version of help) type: bool default: false
    -version (show version and build info and exit) type: bool default: false
```

I'm considering abandoning gflags and maybe looking at a different solution. Having this little control over the help format coupled with the poor formatting decisions seems maybe like too many CONS. 

Also, the spiritual successor to gflags appears to be abseil's flags (https://abseil.io/docs/cpp/guides/flags). I don't think we want to link against all of abseil? Not sure if there is a way to just link to a portion of it.

cxxopts seems pretty popular. Maybe it is a better choice, but I haven't looked at it much yet. https://github.com/jarro2783/cxxopts

**Comment by DanRStevens** [comment]
Sounds like a pretty good summary.

I don't know about linking just part of Abseil. I've heard it's a pretty big library. I've never worked with it before, so I don't know much about using it. I notice they also use macros to define the options. I read through a bit of their documentation. They had an interesting section about considering if you even need flags.

I kind of like the cxxopts syntax. Seems they avoid C macros, and instead make use of C++ templates. The syntax looks a little more natural for a C++ project.

----

In terms of Abseil's recommendation about avoiding flags if possible, that raises an interesting point. Do we really need so many flags? And if so, is this the time to add them? Right now we don't have parsing code for the custom bitmap format. Maybe we should prioritize that first, and use it to guide us on what flags we need. For instance, we can probably get away without a flag to access the archives if that is default behaviour. Considering unpacked files have priority over packed files, it shouldn't really matter if the user can't disable checking the archives. At most, it might impact the speed, but not likely by ever as much time as it would take to type the flag.

I'm wondering if we should start with simple positional arguments for a single use case:
```shell
OP2BitmapConverter inputFile outputFile
```

Of course, if flags are on your mind, and that's the problem you really want to work on, then have at it.

**Comment by Brett208** [comment]
I'm going to close this branch for now and try to wrap up the project without flags. If anyone is looking for addition of some flags, we work a solution then.
